### PR TITLE
Unit tested all usecases

### PR DESCRIPTION
**Pull request by Ram-Raghav-S**

### CODE REVIEW

**Review by muhammadIbrahim-cpu — APPROVED** [review]
Looks good to me.

**Comment by vivic04** [comment]
Overall, the code seems to be well-structured and adheres to some good practices. However one concern I have is that everything is made into a single PR. The issue with this is the it is very easy to introduce a bug into the code by a single mistake. To make this better, we can then split these tests into an individual PR for each use case and preferably much before the deadline for the project.

**Comment by vivic04** [comment]
1. LoginInteractorTest:
The test prepareSuccessResponse is asserting the same condition twice. It seems like there might be a typo. Please verify if this is intentional.
Instead of using assert, consider using the JUnit assertions (assertTrue, assertFalse, etc.) for better failure messages and compatibility with other testing frameworks.

**Comment by vivic04** [comment]
InMemoryCourseDataAccessObject:
In the save method, the logic for setting the course ID seems a bit convoluted. Consider simplifying it for better readability.

**Comment by vivic04** [comment]
InMemorySessionDataAccessObject:
Consider handling the increment of nextID in a more controlled way, possibly in a separate method. This can improve clarity and make the code more maintainable

**Comment by vivic04** [comment]
EndSessionInteractorTest:
In the successTest method, consider using the assertEquals method instead of direct assertions for better failure messages.
It's a good practice to use more descriptive names for test methods. For example, instead of successTest, consider a name that describes the specific scenario being tested.

**Comment by vivic04** [comment]
In the failureSameSessionTwice method, there seems to be an incomplete statement at the end (EndSessionInteractor interactor2 = new EndSessionInteractor(sessionRepository, courseRepository, failurePresenter);). Please complete or remove it.

**Comment by vivic04** [comment]
If these changes are made, everything else seems good to go!

**Pull request merged**
